export const LOGO_HOLD_SECONDS = 1.85;
export const LOGO_STRING_START_SECONDS = 0.68;
export const LOGO_STRING_INTERVAL_SECONDS = 0.09;
export const LOGO_RESOLVE_PAUSE_SECONDS = 0.38;

export const LOGO_STRING_DELAYS = Array.from(
  { length: 6 },
  (_, index) => LOGO_STRING_START_SECONDS + index * LOGO_STRING_INTERVAL_SECONDS,
);

export const LOGO_RESOLVE_SECONDS = LOGO_STRING_START_SECONDS
  + (LOGO_STRING_DELAYS.length - 1) * LOGO_STRING_INTERVAL_SECONDS
  + LOGO_RESOLVE_PAUSE_SECONDS;
